apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: pipeline
  name: pipeline
  namespace: default
spec:
  selector:
    matchLabels:
      app: pipeline
  template:
    metadata:
      labels:
        app: pipeline
    spec:
      containers:
      - image: gcr.io/pipeline-tutorial-218814/pipeline:4c6b4b112a0e6f813a4fe85cab02db11f6cd0403
        name: pipeline
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
